// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: base.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message types enum
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	// Authentication messages (1-99)
	MessageType_MESSAGE_TYPE_AUTH_LOGIN_REQUEST          MessageType = 1
	MessageType_MESSAGE_TYPE_AUTH_LOGIN_RESPONSE         MessageType = 2
	MessageType_MESSAGE_TYPE_AUTH_REGISTER_REQUEST       MessageType = 3
	MessageType_MESSAGE_TYPE_AUTH_REGISTER_RESPONSE      MessageType = 4
	MessageType_MESSAGE_TYPE_AUTH_LOGOUT_REQUEST         MessageType = 5
	MessageType_MESSAGE_TYPE_AUTH_LOGOUT_RESPONSE        MessageType = 6
	MessageType_MESSAGE_TYPE_AUTH_REFRESH_TOKEN_REQUEST  MessageType = 7
	MessageType_MESSAGE_TYPE_AUTH_REFRESH_TOKEN_RESPONSE MessageType = 8
	// Character messages (100-199)
	MessageType_MESSAGE_TYPE_CHARACTER_LIST_REQUEST    MessageType = 100
	MessageType_MESSAGE_TYPE_CHARACTER_LIST_RESPONSE   MessageType = 101
	MessageType_MESSAGE_TYPE_CHARACTER_CREATE_REQUEST  MessageType = 102
	MessageType_MESSAGE_TYPE_CHARACTER_CREATE_RESPONSE MessageType = 103
	MessageType_MESSAGE_TYPE_CHARACTER_DELETE_REQUEST  MessageType = 104
	MessageType_MESSAGE_TYPE_CHARACTER_DELETE_RESPONSE MessageType = 105
	MessageType_MESSAGE_TYPE_CHARACTER_SELECT_REQUEST  MessageType = 106
	MessageType_MESSAGE_TYPE_CHARACTER_SELECT_RESPONSE MessageType = 107
	// World messages (200-299)
	MessageType_MESSAGE_TYPE_WORLD_ENTER_REQUEST   MessageType = 200
	MessageType_MESSAGE_TYPE_WORLD_ENTER_RESPONSE  MessageType = 201
	MessageType_MESSAGE_TYPE_WORLD_LEAVE_REQUEST   MessageType = 202
	MessageType_MESSAGE_TYPE_WORLD_LEAVE_RESPONSE  MessageType = 203
	MessageType_MESSAGE_TYPE_WORLD_POSITION_UPDATE MessageType = 204
	MessageType_MESSAGE_TYPE_WORLD_AREA_UPDATE     MessageType = 205
	MessageType_MESSAGE_TYPE_WORLD_ENTITY_SPAWN    MessageType = 206
	MessageType_MESSAGE_TYPE_WORLD_ENTITY_DESPAWN  MessageType = 207
	// Game messages (300-399)
	MessageType_MESSAGE_TYPE_GAME_ACTION_REQUEST   MessageType = 300
	MessageType_MESSAGE_TYPE_GAME_ACTION_RESPONSE  MessageType = 301
	MessageType_MESSAGE_TYPE_GAME_INVENTORY_UPDATE MessageType = 302
	MessageType_MESSAGE_TYPE_GAME_STATS_UPDATE     MessageType = 303
	MessageType_MESSAGE_TYPE_GAME_QUEST_UPDATE     MessageType = 304
	MessageType_MESSAGE_TYPE_GAME_COMBAT_ACTION    MessageType = 305
	MessageType_MESSAGE_TYPE_GAME_COMBAT_RESULT    MessageType = 306
	// Chat messages (400-499)
	MessageType_MESSAGE_TYPE_CHAT_MESSAGE       MessageType = 400
	MessageType_MESSAGE_TYPE_CHAT_WHISPER       MessageType = 401
	MessageType_MESSAGE_TYPE_CHAT_CHANNEL_JOIN  MessageType = 402
	MessageType_MESSAGE_TYPE_CHAT_CHANNEL_LEAVE MessageType = 403
	MessageType_MESSAGE_TYPE_CHAT_CHANNEL_LIST  MessageType = 404
	// System messages (500-599)
	MessageType_MESSAGE_TYPE_SYSTEM_PING          MessageType = 500
	MessageType_MESSAGE_TYPE_SYSTEM_PONG          MessageType = 501
	MessageType_MESSAGE_TYPE_SYSTEM_ERROR         MessageType = 502
	MessageType_MESSAGE_TYPE_SYSTEM_NOTIFICATION  MessageType = 503
	MessageType_MESSAGE_TYPE_SYSTEM_MAINTENANCE   MessageType = 504
	MessageType_MESSAGE_TYPE_SYSTEM_VERSION_CHECK MessageType = 505
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:   "MESSAGE_TYPE_UNSPECIFIED",
		1:   "MESSAGE_TYPE_AUTH_LOGIN_REQUEST",
		2:   "MESSAGE_TYPE_AUTH_LOGIN_RESPONSE",
		3:   "MESSAGE_TYPE_AUTH_REGISTER_REQUEST",
		4:   "MESSAGE_TYPE_AUTH_REGISTER_RESPONSE",
		5:   "MESSAGE_TYPE_AUTH_LOGOUT_REQUEST",
		6:   "MESSAGE_TYPE_AUTH_LOGOUT_RESPONSE",
		7:   "MESSAGE_TYPE_AUTH_REFRESH_TOKEN_REQUEST",
		8:   "MESSAGE_TYPE_AUTH_REFRESH_TOKEN_RESPONSE",
		100: "MESSAGE_TYPE_CHARACTER_LIST_REQUEST",
		101: "MESSAGE_TYPE_CHARACTER_LIST_RESPONSE",
		102: "MESSAGE_TYPE_CHARACTER_CREATE_REQUEST",
		103: "MESSAGE_TYPE_CHARACTER_CREATE_RESPONSE",
		104: "MESSAGE_TYPE_CHARACTER_DELETE_REQUEST",
		105: "MESSAGE_TYPE_CHARACTER_DELETE_RESPONSE",
		106: "MESSAGE_TYPE_CHARACTER_SELECT_REQUEST",
		107: "MESSAGE_TYPE_CHARACTER_SELECT_RESPONSE",
		200: "MESSAGE_TYPE_WORLD_ENTER_REQUEST",
		201: "MESSAGE_TYPE_WORLD_ENTER_RESPONSE",
		202: "MESSAGE_TYPE_WORLD_LEAVE_REQUEST",
		203: "MESSAGE_TYPE_WORLD_LEAVE_RESPONSE",
		204: "MESSAGE_TYPE_WORLD_POSITION_UPDATE",
		205: "MESSAGE_TYPE_WORLD_AREA_UPDATE",
		206: "MESSAGE_TYPE_WORLD_ENTITY_SPAWN",
		207: "MESSAGE_TYPE_WORLD_ENTITY_DESPAWN",
		300: "MESSAGE_TYPE_GAME_ACTION_REQUEST",
		301: "MESSAGE_TYPE_GAME_ACTION_RESPONSE",
		302: "MESSAGE_TYPE_GAME_INVENTORY_UPDATE",
		303: "MESSAGE_TYPE_GAME_STATS_UPDATE",
		304: "MESSAGE_TYPE_GAME_QUEST_UPDATE",
		305: "MESSAGE_TYPE_GAME_COMBAT_ACTION",
		306: "MESSAGE_TYPE_GAME_COMBAT_RESULT",
		400: "MESSAGE_TYPE_CHAT_MESSAGE",
		401: "MESSAGE_TYPE_CHAT_WHISPER",
		402: "MESSAGE_TYPE_CHAT_CHANNEL_JOIN",
		403: "MESSAGE_TYPE_CHAT_CHANNEL_LEAVE",
		404: "MESSAGE_TYPE_CHAT_CHANNEL_LIST",
		500: "MESSAGE_TYPE_SYSTEM_PING",
		501: "MESSAGE_TYPE_SYSTEM_PONG",
		502: "MESSAGE_TYPE_SYSTEM_ERROR",
		503: "MESSAGE_TYPE_SYSTEM_NOTIFICATION",
		504: "MESSAGE_TYPE_SYSTEM_MAINTENANCE",
		505: "MESSAGE_TYPE_SYSTEM_VERSION_CHECK",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":                 0,
		"MESSAGE_TYPE_AUTH_LOGIN_REQUEST":          1,
		"MESSAGE_TYPE_AUTH_LOGIN_RESPONSE":         2,
		"MESSAGE_TYPE_AUTH_REGISTER_REQUEST":       3,
		"MESSAGE_TYPE_AUTH_REGISTER_RESPONSE":      4,
		"MESSAGE_TYPE_AUTH_LOGOUT_REQUEST":         5,
		"MESSAGE_TYPE_AUTH_LOGOUT_RESPONSE":        6,
		"MESSAGE_TYPE_AUTH_REFRESH_TOKEN_REQUEST":  7,
		"MESSAGE_TYPE_AUTH_REFRESH_TOKEN_RESPONSE": 8,
		"MESSAGE_TYPE_CHARACTER_LIST_REQUEST":      100,
		"MESSAGE_TYPE_CHARACTER_LIST_RESPONSE":     101,
		"MESSAGE_TYPE_CHARACTER_CREATE_REQUEST":    102,
		"MESSAGE_TYPE_CHARACTER_CREATE_RESPONSE":   103,
		"MESSAGE_TYPE_CHARACTER_DELETE_REQUEST":    104,
		"MESSAGE_TYPE_CHARACTER_DELETE_RESPONSE":   105,
		"MESSAGE_TYPE_CHARACTER_SELECT_REQUEST":    106,
		"MESSAGE_TYPE_CHARACTER_SELECT_RESPONSE":   107,
		"MESSAGE_TYPE_WORLD_ENTER_REQUEST":         200,
		"MESSAGE_TYPE_WORLD_ENTER_RESPONSE":        201,
		"MESSAGE_TYPE_WORLD_LEAVE_REQUEST":         202,
		"MESSAGE_TYPE_WORLD_LEAVE_RESPONSE":        203,
		"MESSAGE_TYPE_WORLD_POSITION_UPDATE":       204,
		"MESSAGE_TYPE_WORLD_AREA_UPDATE":           205,
		"MESSAGE_TYPE_WORLD_ENTITY_SPAWN":          206,
		"MESSAGE_TYPE_WORLD_ENTITY_DESPAWN":        207,
		"MESSAGE_TYPE_GAME_ACTION_REQUEST":         300,
		"MESSAGE_TYPE_GAME_ACTION_RESPONSE":        301,
		"MESSAGE_TYPE_GAME_INVENTORY_UPDATE":       302,
		"MESSAGE_TYPE_GAME_STATS_UPDATE":           303,
		"MESSAGE_TYPE_GAME_QUEST_UPDATE":           304,
		"MESSAGE_TYPE_GAME_COMBAT_ACTION":          305,
		"MESSAGE_TYPE_GAME_COMBAT_RESULT":          306,
		"MESSAGE_TYPE_CHAT_MESSAGE":                400,
		"MESSAGE_TYPE_CHAT_WHISPER":                401,
		"MESSAGE_TYPE_CHAT_CHANNEL_JOIN":           402,
		"MESSAGE_TYPE_CHAT_CHANNEL_LEAVE":          403,
		"MESSAGE_TYPE_CHAT_CHANNEL_LIST":           404,
		"MESSAGE_TYPE_SYSTEM_PING":                 500,
		"MESSAGE_TYPE_SYSTEM_PONG":                 501,
		"MESSAGE_TYPE_SYSTEM_ERROR":                502,
		"MESSAGE_TYPE_SYSTEM_NOTIFICATION":         503,
		"MESSAGE_TYPE_SYSTEM_MAINTENANCE":          504,
		"MESSAGE_TYPE_SYSTEM_VERSION_CHECK":        505,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_base_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_base_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{0}
}

// Common error codes
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED             ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_REQUEST         ErrorCode = 1
	ErrorCode_ERROR_CODE_UNAUTHORIZED            ErrorCode = 2
	ErrorCode_ERROR_CODE_FORBIDDEN               ErrorCode = 3
	ErrorCode_ERROR_CODE_NOT_FOUND               ErrorCode = 4
	ErrorCode_ERROR_CODE_ALREADY_EXISTS          ErrorCode = 5
	ErrorCode_ERROR_CODE_RATE_LIMITED            ErrorCode = 6
	ErrorCode_ERROR_CODE_SERVER_ERROR            ErrorCode = 7
	ErrorCode_ERROR_CODE_SERVICE_UNAVAILABLE     ErrorCode = 8
	ErrorCode_ERROR_CODE_TIMEOUT                 ErrorCode = 9
	ErrorCode_ERROR_CODE_INVALID_CREDENTIALS     ErrorCode = 10
	ErrorCode_ERROR_CODE_ACCOUNT_LOCKED          ErrorCode = 11
	ErrorCode_ERROR_CODE_CHARACTER_LIMIT_REACHED ErrorCode = 12
	ErrorCode_ERROR_CODE_INVALID_CHARACTER_NAME  ErrorCode = 13
	ErrorCode_ERROR_CODE_WORLD_FULL              ErrorCode = 14
	ErrorCode_ERROR_CODE_INVALID_ACTION          ErrorCode = 15
	ErrorCode_ERROR_CODE_INSUFFICIENT_RESOURCES  ErrorCode = 16
	ErrorCode_ERROR_CODE_INVENTORY_FULL          ErrorCode = 17
	ErrorCode_ERROR_CODE_QUEST_NOT_AVAILABLE     ErrorCode = 18
	ErrorCode_ERROR_CODE_COMBAT_NOT_ALLOWED      ErrorCode = 19
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_CODE_UNSPECIFIED",
		1:  "ERROR_CODE_INVALID_REQUEST",
		2:  "ERROR_CODE_UNAUTHORIZED",
		3:  "ERROR_CODE_FORBIDDEN",
		4:  "ERROR_CODE_NOT_FOUND",
		5:  "ERROR_CODE_ALREADY_EXISTS",
		6:  "ERROR_CODE_RATE_LIMITED",
		7:  "ERROR_CODE_SERVER_ERROR",
		8:  "ERROR_CODE_SERVICE_UNAVAILABLE",
		9:  "ERROR_CODE_TIMEOUT",
		10: "ERROR_CODE_INVALID_CREDENTIALS",
		11: "ERROR_CODE_ACCOUNT_LOCKED",
		12: "ERROR_CODE_CHARACTER_LIMIT_REACHED",
		13: "ERROR_CODE_INVALID_CHARACTER_NAME",
		14: "ERROR_CODE_WORLD_FULL",
		15: "ERROR_CODE_INVALID_ACTION",
		16: "ERROR_CODE_INSUFFICIENT_RESOURCES",
		17: "ERROR_CODE_INVENTORY_FULL",
		18: "ERROR_CODE_QUEST_NOT_AVAILABLE",
		19: "ERROR_CODE_COMBAT_NOT_ALLOWED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":             0,
		"ERROR_CODE_INVALID_REQUEST":         1,
		"ERROR_CODE_UNAUTHORIZED":            2,
		"ERROR_CODE_FORBIDDEN":               3,
		"ERROR_CODE_NOT_FOUND":               4,
		"ERROR_CODE_ALREADY_EXISTS":          5,
		"ERROR_CODE_RATE_LIMITED":            6,
		"ERROR_CODE_SERVER_ERROR":            7,
		"ERROR_CODE_SERVICE_UNAVAILABLE":     8,
		"ERROR_CODE_TIMEOUT":                 9,
		"ERROR_CODE_INVALID_CREDENTIALS":     10,
		"ERROR_CODE_ACCOUNT_LOCKED":          11,
		"ERROR_CODE_CHARACTER_LIMIT_REACHED": 12,
		"ERROR_CODE_INVALID_CHARACTER_NAME":  13,
		"ERROR_CODE_WORLD_FULL":              14,
		"ERROR_CODE_INVALID_ACTION":          15,
		"ERROR_CODE_INSUFFICIENT_RESOURCES":  16,
		"ERROR_CODE_INVENTORY_FULL":          17,
		"ERROR_CODE_QUEST_NOT_AVAILABLE":     18,
		"ERROR_CODE_COMBAT_NOT_ALLOWED":      19,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_base_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_base_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{1}
}

// Base message envelope for all game communications
type GameMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Version   uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                   // Protocol version
	Sequence  uint32                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`                 // Message sequence number
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                // Message timestamp
	Type      MessageType            `protobuf:"varint,4,opt,name=type,proto3,enum=mmorpg.MessageType" json:"type,omitempty"` // Message type
	Payload   []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`                    // Actual message data (serialized specific message)
	// Optional fields for reliability
	AckSequence   *uint32 `protobuf:"varint,6,opt,name=ack_sequence,json=ackSequence,proto3,oneof" json:"ack_sequence,omitempty"` // Acknowledge received message
	RequiresAck   *bool   `protobuf:"varint,7,opt,name=requires_ack,json=requiresAck,proto3,oneof" json:"requires_ack,omitempty"` // Whether this message requires acknowledgment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{0}
}

func (x *GameMessage) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GameMessage) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *GameMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GameMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *GameMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GameMessage) GetAckSequence() uint32 {
	if x != nil && x.AckSequence != nil {
		return *x.AckSequence
	}
	return 0
}

func (x *GameMessage) GetRequiresAck() bool {
	if x != nil && x.RequiresAck != nil {
		return *x.RequiresAck
	}
	return false
}

// Common data structures
type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{1}
}

func (x *Vector3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Rotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Yaw           float32                `protobuf:"fixed32,1,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch         float32                `protobuf:"fixed32,2,opt,name=pitch,proto3" json:"pitch,omitempty"`
	Roll          float32                `protobuf:"fixed32,3,opt,name=roll,proto3" json:"roll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rotation) Reset() {
	*x = Rotation{}
	mi := &file_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rotation) ProtoMessage() {}

func (x *Rotation) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rotation.ProtoReflect.Descriptor instead.
func (*Rotation) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{2}
}

func (x *Rotation) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *Rotation) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *Rotation) GetRoll() float32 {
	if x != nil {
		return x.Roll
	}
	return 0
}

type Transform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Vector3               `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Rotation      *Rotation              `protobuf:"bytes,2,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Scale         *Vector3               `protobuf:"bytes,3,opt,name=scale,proto3" json:"scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transform) Reset() {
	*x = Transform{}
	mi := &file_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transform) ProtoMessage() {}

func (x *Transform) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transform.ProtoReflect.Descriptor instead.
func (*Transform) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{3}
}

func (x *Transform) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Transform) GetRotation() *Rotation {
	if x != nil {
		return x.Rotation
	}
	return nil
}

func (x *Transform) GetScale() *Vector3 {
	if x != nil {
		return x.Scale
	}
	return nil
}

// Base error response
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=mmorpg.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_base_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{4}
}

func (x *ErrorResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_base_proto protoreflect.FileDescriptor

const file_base_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"base.proto\x12\x06mmorpg\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x02\n" +
	"\vGameMessage\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\rR\bsequence\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12'\n" +
	"\x04type\x18\x04 \x01(\x0e2\x13.mmorpg.MessageTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12&\n" +
	"\fack_sequence\x18\x06 \x01(\rH\x00R\vackSequence\x88\x01\x01\x12&\n" +
	"\frequires_ack\x18\a \x01(\bH\x01R\vrequiresAck\x88\x01\x01B\x0f\n" +
	"\r_ack_sequenceB\x0f\n" +
	"\r_requires_ack\"3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"F\n" +
	"\bRotation\x12\x10\n" +
	"\x03yaw\x18\x01 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x02 \x01(\x02R\x05pitch\x12\x12\n" +
	"\x04roll\x18\x03 \x01(\x02R\x04roll\"\x8d\x01\n" +
	"\tTransform\x12+\n" +
	"\bposition\x18\x01 \x01(\v2\x0f.mmorpg.Vector3R\bposition\x12,\n" +
	"\brotation\x18\x02 \x01(\v2\x10.mmorpg.RotationR\brotation\x12%\n" +
	"\x05scale\x18\x03 \x01(\v2\x0f.mmorpg.Vector3R\x05scale\"\xca\x01\n" +
	"\rErrorResponse\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.mmorpg.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\adetails\x18\x03 \x03(\v2\".mmorpg.ErrorResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x92\r\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fMESSAGE_TYPE_AUTH_LOGIN_REQUEST\x10\x01\x12$\n" +
	" MESSAGE_TYPE_AUTH_LOGIN_RESPONSE\x10\x02\x12&\n" +
	"\"MESSAGE_TYPE_AUTH_REGISTER_REQUEST\x10\x03\x12'\n" +
	"#MESSAGE_TYPE_AUTH_REGISTER_RESPONSE\x10\x04\x12$\n" +
	" MESSAGE_TYPE_AUTH_LOGOUT_REQUEST\x10\x05\x12%\n" +
	"!MESSAGE_TYPE_AUTH_LOGOUT_RESPONSE\x10\x06\x12+\n" +
	"'MESSAGE_TYPE_AUTH_REFRESH_TOKEN_REQUEST\x10\a\x12,\n" +
	"(MESSAGE_TYPE_AUTH_REFRESH_TOKEN_RESPONSE\x10\b\x12'\n" +
	"#MESSAGE_TYPE_CHARACTER_LIST_REQUEST\x10d\x12(\n" +
	"$MESSAGE_TYPE_CHARACTER_LIST_RESPONSE\x10e\x12)\n" +
	"%MESSAGE_TYPE_CHARACTER_CREATE_REQUEST\x10f\x12*\n" +
	"&MESSAGE_TYPE_CHARACTER_CREATE_RESPONSE\x10g\x12)\n" +
	"%MESSAGE_TYPE_CHARACTER_DELETE_REQUEST\x10h\x12*\n" +
	"&MESSAGE_TYPE_CHARACTER_DELETE_RESPONSE\x10i\x12)\n" +
	"%MESSAGE_TYPE_CHARACTER_SELECT_REQUEST\x10j\x12*\n" +
	"&MESSAGE_TYPE_CHARACTER_SELECT_RESPONSE\x10k\x12%\n" +
	" MESSAGE_TYPE_WORLD_ENTER_REQUEST\x10\xc8\x01\x12&\n" +
	"!MESSAGE_TYPE_WORLD_ENTER_RESPONSE\x10\xc9\x01\x12%\n" +
	" MESSAGE_TYPE_WORLD_LEAVE_REQUEST\x10\xca\x01\x12&\n" +
	"!MESSAGE_TYPE_WORLD_LEAVE_RESPONSE\x10\xcb\x01\x12'\n" +
	"\"MESSAGE_TYPE_WORLD_POSITION_UPDATE\x10\xcc\x01\x12#\n" +
	"\x1eMESSAGE_TYPE_WORLD_AREA_UPDATE\x10\xcd\x01\x12$\n" +
	"\x1fMESSAGE_TYPE_WORLD_ENTITY_SPAWN\x10\xce\x01\x12&\n" +
	"!MESSAGE_TYPE_WORLD_ENTITY_DESPAWN\x10\xcf\x01\x12%\n" +
	" MESSAGE_TYPE_GAME_ACTION_REQUEST\x10\xac\x02\x12&\n" +
	"!MESSAGE_TYPE_GAME_ACTION_RESPONSE\x10\xad\x02\x12'\n" +
	"\"MESSAGE_TYPE_GAME_INVENTORY_UPDATE\x10\xae\x02\x12#\n" +
	"\x1eMESSAGE_TYPE_GAME_STATS_UPDATE\x10\xaf\x02\x12#\n" +
	"\x1eMESSAGE_TYPE_GAME_QUEST_UPDATE\x10\xb0\x02\x12$\n" +
	"\x1fMESSAGE_TYPE_GAME_COMBAT_ACTION\x10\xb1\x02\x12$\n" +
	"\x1fMESSAGE_TYPE_GAME_COMBAT_RESULT\x10\xb2\x02\x12\x1e\n" +
	"\x19MESSAGE_TYPE_CHAT_MESSAGE\x10\x90\x03\x12\x1e\n" +
	"\x19MESSAGE_TYPE_CHAT_WHISPER\x10\x91\x03\x12#\n" +
	"\x1eMESSAGE_TYPE_CHAT_CHANNEL_JOIN\x10\x92\x03\x12$\n" +
	"\x1fMESSAGE_TYPE_CHAT_CHANNEL_LEAVE\x10\x93\x03\x12#\n" +
	"\x1eMESSAGE_TYPE_CHAT_CHANNEL_LIST\x10\x94\x03\x12\x1d\n" +
	"\x18MESSAGE_TYPE_SYSTEM_PING\x10\xf4\x03\x12\x1d\n" +
	"\x18MESSAGE_TYPE_SYSTEM_PONG\x10\xf5\x03\x12\x1e\n" +
	"\x19MESSAGE_TYPE_SYSTEM_ERROR\x10\xf6\x03\x12%\n" +
	" MESSAGE_TYPE_SYSTEM_NOTIFICATION\x10\xf7\x03\x12$\n" +
	"\x1fMESSAGE_TYPE_SYSTEM_MAINTENANCE\x10\xf8\x03\x12&\n" +
	"!MESSAGE_TYPE_SYSTEM_VERSION_CHECK\x10\xf9\x03*\x86\x05\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aERROR_CODE_INVALID_REQUEST\x10\x01\x12\x1b\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\x02\x12\x18\n" +
	"\x14ERROR_CODE_FORBIDDEN\x10\x03\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x04\x12\x1d\n" +
	"\x19ERROR_CODE_ALREADY_EXISTS\x10\x05\x12\x1b\n" +
	"\x17ERROR_CODE_RATE_LIMITED\x10\x06\x12\x1b\n" +
	"\x17ERROR_CODE_SERVER_ERROR\x10\a\x12\"\n" +
	"\x1eERROR_CODE_SERVICE_UNAVAILABLE\x10\b\x12\x16\n" +
	"\x12ERROR_CODE_TIMEOUT\x10\t\x12\"\n" +
	"\x1eERROR_CODE_INVALID_CREDENTIALS\x10\n" +
	"\x12\x1d\n" +
	"\x19ERROR_CODE_ACCOUNT_LOCKED\x10\v\x12&\n" +
	"\"ERROR_CODE_CHARACTER_LIMIT_REACHED\x10\f\x12%\n" +
	"!ERROR_CODE_INVALID_CHARACTER_NAME\x10\r\x12\x19\n" +
	"\x15ERROR_CODE_WORLD_FULL\x10\x0e\x12\x1d\n" +
	"\x19ERROR_CODE_INVALID_ACTION\x10\x0f\x12%\n" +
	"!ERROR_CODE_INSUFFICIENT_RESOURCES\x10\x10\x12\x1d\n" +
	"\x19ERROR_CODE_INVENTORY_FULL\x10\x11\x12\"\n" +
	"\x1eERROR_CODE_QUEST_NOT_AVAILABLE\x10\x12\x12!\n" +
	"\x1dERROR_CODE_COMBAT_NOT_ALLOWED\x10\x13B.Z,github.com/mmorpg-template/backend/pkg/protob\x06proto3"

var (
	file_base_proto_rawDescOnce sync.Once
	file_base_proto_rawDescData []byte
)

func file_base_proto_rawDescGZIP() []byte {
	file_base_proto_rawDescOnce.Do(func() {
		file_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_proto_rawDesc), len(file_base_proto_rawDesc)))
	})
	return file_base_proto_rawDescData
}

var file_base_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_base_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_base_proto_goTypes = []any{
	(MessageType)(0),              // 0: mmorpg.MessageType
	(ErrorCode)(0),                // 1: mmorpg.ErrorCode
	(*GameMessage)(nil),           // 2: mmorpg.GameMessage
	(*Vector3)(nil),               // 3: mmorpg.Vector3
	(*Rotation)(nil),              // 4: mmorpg.Rotation
	(*Transform)(nil),             // 5: mmorpg.Transform
	(*ErrorResponse)(nil),         // 6: mmorpg.ErrorResponse
	nil,                           // 7: mmorpg.ErrorResponse.DetailsEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_base_proto_depIdxs = []int32{
	8, // 0: mmorpg.GameMessage.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: mmorpg.GameMessage.type:type_name -> mmorpg.MessageType
	3, // 2: mmorpg.Transform.position:type_name -> mmorpg.Vector3
	4, // 3: mmorpg.Transform.rotation:type_name -> mmorpg.Rotation
	3, // 4: mmorpg.Transform.scale:type_name -> mmorpg.Vector3
	1, // 5: mmorpg.ErrorResponse.code:type_name -> mmorpg.ErrorCode
	7, // 6: mmorpg.ErrorResponse.details:type_name -> mmorpg.ErrorResponse.DetailsEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_base_proto_init() }
func file_base_proto_init() {
	if File_base_proto != nil {
		return
	}
	file_base_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_proto_rawDesc), len(file_base_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_proto_goTypes,
		DependencyIndexes: file_base_proto_depIdxs,
		EnumInfos:         file_base_proto_enumTypes,
		MessageInfos:      file_base_proto_msgTypes,
	}.Build()
	File_base_proto = out.File
	file_base_proto_goTypes = nil
	file_base_proto_depIdxs = nil
}
