// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: character.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Character classes
type CharacterClass int32

const (
	CharacterClass_CHARACTER_CLASS_UNSPECIFIED CharacterClass = 0
	CharacterClass_CHARACTER_CLASS_WARRIOR     CharacterClass = 1
	CharacterClass_CHARACTER_CLASS_MAGE        CharacterClass = 2
	CharacterClass_CHARACTER_CLASS_ARCHER      CharacterClass = 3
	CharacterClass_CHARACTER_CLASS_ROGUE       CharacterClass = 4
	CharacterClass_CHARACTER_CLASS_PRIEST      CharacterClass = 5
	CharacterClass_CHARACTER_CLASS_PALADIN     CharacterClass = 6
	CharacterClass_CHARACTER_CLASS_WARLOCK     CharacterClass = 7
	CharacterClass_CHARACTER_CLASS_DRUID       CharacterClass = 8
)

// Enum value maps for CharacterClass.
var (
	CharacterClass_name = map[int32]string{
		0: "CHARACTER_CLASS_UNSPECIFIED",
		1: "CHARACTER_CLASS_WARRIOR",
		2: "CHARACTER_CLASS_MAGE",
		3: "CHARACTER_CLASS_ARCHER",
		4: "CHARACTER_CLASS_ROGUE",
		5: "CHARACTER_CLASS_PRIEST",
		6: "CHARACTER_CLASS_PALADIN",
		7: "CHARACTER_CLASS_WARLOCK",
		8: "CHARACTER_CLASS_DRUID",
	}
	CharacterClass_value = map[string]int32{
		"CHARACTER_CLASS_UNSPECIFIED": 0,
		"CHARACTER_CLASS_WARRIOR":     1,
		"CHARACTER_CLASS_MAGE":        2,
		"CHARACTER_CLASS_ARCHER":      3,
		"CHARACTER_CLASS_ROGUE":       4,
		"CHARACTER_CLASS_PRIEST":      5,
		"CHARACTER_CLASS_PALADIN":     6,
		"CHARACTER_CLASS_WARLOCK":     7,
		"CHARACTER_CLASS_DRUID":       8,
	}
)

func (x CharacterClass) Enum() *CharacterClass {
	p := new(CharacterClass)
	*p = x
	return p
}

func (x CharacterClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CharacterClass) Descriptor() protoreflect.EnumDescriptor {
	return file_character_proto_enumTypes[0].Descriptor()
}

func (CharacterClass) Type() protoreflect.EnumType {
	return &file_character_proto_enumTypes[0]
}

func (x CharacterClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CharacterClass.Descriptor instead.
func (CharacterClass) EnumDescriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{0}
}

// Character races
type CharacterRace int32

const (
	CharacterRace_CHARACTER_RACE_UNSPECIFIED CharacterRace = 0
	CharacterRace_CHARACTER_RACE_HUMAN       CharacterRace = 1
	CharacterRace_CHARACTER_RACE_ELF         CharacterRace = 2
	CharacterRace_CHARACTER_RACE_DWARF       CharacterRace = 3
	CharacterRace_CHARACTER_RACE_ORC         CharacterRace = 4
	CharacterRace_CHARACTER_RACE_GNOME       CharacterRace = 5
	CharacterRace_CHARACTER_RACE_UNDEAD      CharacterRace = 6
	CharacterRace_CHARACTER_RACE_TROLL       CharacterRace = 7
	CharacterRace_CHARACTER_RACE_HALFLING    CharacterRace = 8
)

// Enum value maps for CharacterRace.
var (
	CharacterRace_name = map[int32]string{
		0: "CHARACTER_RACE_UNSPECIFIED",
		1: "CHARACTER_RACE_HUMAN",
		2: "CHARACTER_RACE_ELF",
		3: "CHARACTER_RACE_DWARF",
		4: "CHARACTER_RACE_ORC",
		5: "CHARACTER_RACE_GNOME",
		6: "CHARACTER_RACE_UNDEAD",
		7: "CHARACTER_RACE_TROLL",
		8: "CHARACTER_RACE_HALFLING",
	}
	CharacterRace_value = map[string]int32{
		"CHARACTER_RACE_UNSPECIFIED": 0,
		"CHARACTER_RACE_HUMAN":       1,
		"CHARACTER_RACE_ELF":         2,
		"CHARACTER_RACE_DWARF":       3,
		"CHARACTER_RACE_ORC":         4,
		"CHARACTER_RACE_GNOME":       5,
		"CHARACTER_RACE_UNDEAD":      6,
		"CHARACTER_RACE_TROLL":       7,
		"CHARACTER_RACE_HALFLING":    8,
	}
)

func (x CharacterRace) Enum() *CharacterRace {
	p := new(CharacterRace)
	*p = x
	return p
}

func (x CharacterRace) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CharacterRace) Descriptor() protoreflect.EnumDescriptor {
	return file_character_proto_enumTypes[1].Descriptor()
}

func (CharacterRace) Type() protoreflect.EnumType {
	return &file_character_proto_enumTypes[1]
}

func (x CharacterRace) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CharacterRace.Descriptor instead.
func (CharacterRace) EnumDescriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{1}
}

// Gender
type Gender int32

const (
	Gender_GENDER_UNSPECIFIED Gender = 0
	Gender_GENDER_MALE        Gender = 1
	Gender_GENDER_FEMALE      Gender = 2
	Gender_GENDER_OTHER       Gender = 3
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
		3: "GENDER_OTHER",
	}
	Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FEMALE":      2,
		"GENDER_OTHER":       3,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_character_proto_enumTypes[2].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_character_proto_enumTypes[2]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{2}
}

// List characters request
type CharacterListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterListRequest) Reset() {
	*x = CharacterListRequest{}
	mi := &file_character_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterListRequest) ProtoMessage() {}

func (x *CharacterListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterListRequest.ProtoReflect.Descriptor instead.
func (*CharacterListRequest) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{0}
}

func (x *CharacterListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CharacterListRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// List characters response
type CharacterListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Characters    []*CharacterInfo       `protobuf:"bytes,2,rep,name=characters,proto3" json:"characters,omitempty"`
	MaxCharacters int32                  `protobuf:"varint,3,opt,name=max_characters,json=maxCharacters,proto3" json:"max_characters,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode     ErrorCode              `protobuf:"varint,5,opt,name=error_code,json=errorCode,proto3,enum=mmorpg.ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterListResponse) Reset() {
	*x = CharacterListResponse{}
	mi := &file_character_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterListResponse) ProtoMessage() {}

func (x *CharacterListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterListResponse.ProtoReflect.Descriptor instead.
func (*CharacterListResponse) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{1}
}

func (x *CharacterListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CharacterListResponse) GetCharacters() []*CharacterInfo {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *CharacterListResponse) GetMaxCharacters() int32 {
	if x != nil {
		return x.MaxCharacters
	}
	return 0
}

func (x *CharacterListResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CharacterListResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// Create character request
type CharacterCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Class         CharacterClass         `protobuf:"varint,2,opt,name=class,proto3,enum=mmorpg.CharacterClass" json:"class,omitempty"`
	Race          CharacterRace          `protobuf:"varint,3,opt,name=race,proto3,enum=mmorpg.CharacterRace" json:"race,omitempty"`
	Gender        Gender                 `protobuf:"varint,4,opt,name=gender,proto3,enum=mmorpg.Gender" json:"gender,omitempty"`
	Appearance    *CharacterAppearance   `protobuf:"bytes,5,opt,name=appearance,proto3" json:"appearance,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterCreateRequest) Reset() {
	*x = CharacterCreateRequest{}
	mi := &file_character_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterCreateRequest) ProtoMessage() {}

func (x *CharacterCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterCreateRequest.ProtoReflect.Descriptor instead.
func (*CharacterCreateRequest) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{2}
}

func (x *CharacterCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterCreateRequest) GetClass() CharacterClass {
	if x != nil {
		return x.Class
	}
	return CharacterClass_CHARACTER_CLASS_UNSPECIFIED
}

func (x *CharacterCreateRequest) GetRace() CharacterRace {
	if x != nil {
		return x.Race
	}
	return CharacterRace_CHARACTER_RACE_UNSPECIFIED
}

func (x *CharacterCreateRequest) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *CharacterCreateRequest) GetAppearance() *CharacterAppearance {
	if x != nil {
		return x.Appearance
	}
	return nil
}

func (x *CharacterCreateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Create character response
type CharacterCreateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Character        *CharacterInfo         `protobuf:"bytes,2,opt,name=character,proto3" json:"character,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode        ErrorCode              `protobuf:"varint,4,opt,name=error_code,json=errorCode,proto3,enum=mmorpg.ErrorCode" json:"error_code,omitempty"`
	ValidationErrors map[string]string      `protobuf:"bytes,5,rep,name=validation_errors,json=validationErrors,proto3" json:"validation_errors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CharacterCreateResponse) Reset() {
	*x = CharacterCreateResponse{}
	mi := &file_character_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterCreateResponse) ProtoMessage() {}

func (x *CharacterCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterCreateResponse.ProtoReflect.Descriptor instead.
func (*CharacterCreateResponse) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{3}
}

func (x *CharacterCreateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CharacterCreateResponse) GetCharacter() *CharacterInfo {
	if x != nil {
		return x.Character
	}
	return nil
}

func (x *CharacterCreateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CharacterCreateResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *CharacterCreateResponse) GetValidationErrors() map[string]string {
	if x != nil {
		return x.ValidationErrors
	}
	return nil
}

// Delete character request
type CharacterDeleteRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CharacterId      string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	SessionId        string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConfirmationCode string                 `protobuf:"bytes,3,opt,name=confirmation_code,json=confirmationCode,proto3" json:"confirmation_code,omitempty"` // Safety confirmation
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CharacterDeleteRequest) Reset() {
	*x = CharacterDeleteRequest{}
	mi := &file_character_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterDeleteRequest) ProtoMessage() {}

func (x *CharacterDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterDeleteRequest.ProtoReflect.Descriptor instead.
func (*CharacterDeleteRequest) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{4}
}

func (x *CharacterDeleteRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *CharacterDeleteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CharacterDeleteRequest) GetConfirmationCode() string {
	if x != nil {
		return x.ConfirmationCode
	}
	return ""
}

// Delete character response
type CharacterDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     ErrorCode              `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=mmorpg.ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterDeleteResponse) Reset() {
	*x = CharacterDeleteResponse{}
	mi := &file_character_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterDeleteResponse) ProtoMessage() {}

func (x *CharacterDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterDeleteResponse.ProtoReflect.Descriptor instead.
func (*CharacterDeleteResponse) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{5}
}

func (x *CharacterDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CharacterDeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CharacterDeleteResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// Select character request
type CharacterSelectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterSelectRequest) Reset() {
	*x = CharacterSelectRequest{}
	mi := &file_character_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterSelectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterSelectRequest) ProtoMessage() {}

func (x *CharacterSelectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterSelectRequest.ProtoReflect.Descriptor instead.
func (*CharacterSelectRequest) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{6}
}

func (x *CharacterSelectRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *CharacterSelectRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Select character response
type CharacterSelectResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CharacterData  *CharacterData         `protobuf:"bytes,2,opt,name=character_data,json=characterData,proto3" json:"character_data,omitempty"`
	WorldServerUrl string                 `protobuf:"bytes,3,opt,name=world_server_url,json=worldServerUrl,proto3" json:"world_server_url,omitempty"` // Which world server to connect to
	WorldToken     string                 `protobuf:"bytes,4,opt,name=world_token,json=worldToken,proto3" json:"world_token,omitempty"`               // Token for world server authentication
	ErrorMessage   string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode      ErrorCode              `protobuf:"varint,6,opt,name=error_code,json=errorCode,proto3,enum=mmorpg.ErrorCode" json:"error_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CharacterSelectResponse) Reset() {
	*x = CharacterSelectResponse{}
	mi := &file_character_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterSelectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterSelectResponse) ProtoMessage() {}

func (x *CharacterSelectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterSelectResponse.ProtoReflect.Descriptor instead.
func (*CharacterSelectResponse) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{7}
}

func (x *CharacterSelectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CharacterSelectResponse) GetCharacterData() *CharacterData {
	if x != nil {
		return x.CharacterData
	}
	return nil
}

func (x *CharacterSelectResponse) GetWorldServerUrl() string {
	if x != nil {
		return x.WorldServerUrl
	}
	return ""
}

func (x *CharacterSelectResponse) GetWorldToken() string {
	if x != nil {
		return x.WorldToken
	}
	return ""
}

func (x *CharacterSelectResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CharacterSelectResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// Character information (for list/preview)
type CharacterInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CharacterId     string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Class           CharacterClass         `protobuf:"varint,3,opt,name=class,proto3,enum=mmorpg.CharacterClass" json:"class,omitempty"`
	Race            CharacterRace          `protobuf:"varint,4,opt,name=race,proto3,enum=mmorpg.CharacterRace" json:"race,omitempty"`
	Gender          Gender                 `protobuf:"varint,5,opt,name=gender,proto3,enum=mmorpg.Gender" json:"gender,omitempty"`
	Level           int32                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	Location        string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"` // Last known location name
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastPlayed      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_played,json=lastPlayed,proto3" json:"last_played,omitempty"`
	PlaytimeSeconds int64                  `protobuf:"varint,10,opt,name=playtime_seconds,json=playtimeSeconds,proto3" json:"playtime_seconds,omitempty"`
	// Basic appearance for character select screen
	Appearance *CharacterAppearance `protobuf:"bytes,11,opt,name=appearance,proto3" json:"appearance,omitempty"`
	// Equipment preview
	EquipmentPreview []*EquipmentPreview `protobuf:"bytes,12,rep,name=equipment_preview,json=equipmentPreview,proto3" json:"equipment_preview,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CharacterInfo) Reset() {
	*x = CharacterInfo{}
	mi := &file_character_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterInfo) ProtoMessage() {}

func (x *CharacterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterInfo.ProtoReflect.Descriptor instead.
func (*CharacterInfo) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{8}
}

func (x *CharacterInfo) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *CharacterInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterInfo) GetClass() CharacterClass {
	if x != nil {
		return x.Class
	}
	return CharacterClass_CHARACTER_CLASS_UNSPECIFIED
}

func (x *CharacterInfo) GetRace() CharacterRace {
	if x != nil {
		return x.Race
	}
	return CharacterRace_CHARACTER_RACE_UNSPECIFIED
}

func (x *CharacterInfo) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *CharacterInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CharacterInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CharacterInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CharacterInfo) GetLastPlayed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPlayed
	}
	return nil
}

func (x *CharacterInfo) GetPlaytimeSeconds() int64 {
	if x != nil {
		return x.PlaytimeSeconds
	}
	return 0
}

func (x *CharacterInfo) GetAppearance() *CharacterAppearance {
	if x != nil {
		return x.Appearance
	}
	return nil
}

func (x *CharacterInfo) GetEquipmentPreview() []*EquipmentPreview {
	if x != nil {
		return x.EquipmentPreview
	}
	return nil
}

// Full character data (when entering game)
type CharacterData struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CharacterId string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Class       CharacterClass         `protobuf:"varint,3,opt,name=class,proto3,enum=mmorpg.CharacterClass" json:"class,omitempty"`
	Race        CharacterRace          `protobuf:"varint,4,opt,name=race,proto3,enum=mmorpg.CharacterRace" json:"race,omitempty"`
	Gender      Gender                 `protobuf:"varint,5,opt,name=gender,proto3,enum=mmorpg.Gender" json:"gender,omitempty"`
	// Stats
	Stats      *CharacterStats      `protobuf:"bytes,6,opt,name=stats,proto3" json:"stats,omitempty"`
	Attributes *CharacterAttributes `protobuf:"bytes,7,opt,name=attributes,proto3" json:"attributes,omitempty"`
	// Progress
	Level                 int32 `protobuf:"varint,8,opt,name=level,proto3" json:"level,omitempty"`
	Experience            int64 `protobuf:"varint,9,opt,name=experience,proto3" json:"experience,omitempty"`
	ExperienceToNextLevel int64 `protobuf:"varint,10,opt,name=experience_to_next_level,json=experienceToNextLevel,proto3" json:"experience_to_next_level,omitempty"`
	// Location
	LastTransform *Transform `protobuf:"bytes,11,opt,name=last_transform,json=lastTransform,proto3" json:"last_transform,omitempty"`
	LastZoneId    string     `protobuf:"bytes,12,opt,name=last_zone_id,json=lastZoneId,proto3" json:"last_zone_id,omitempty"`
	// Appearance
	Appearance *CharacterAppearance `protobuf:"bytes,13,opt,name=appearance,proto3" json:"appearance,omitempty"`
	// Equipment
	EquippedItems map[string]string `protobuf:"bytes,14,rep,name=equipped_items,json=equippedItems,proto3" json:"equipped_items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // slot -> item_id
	// Currencies
	Currencies map[string]int64 `protobuf:"bytes,15,rep,name=currencies,proto3" json:"currencies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Timestamps
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastPlayed      *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=last_played,json=lastPlayed,proto3" json:"last_played,omitempty"`
	PlaytimeSeconds int64                  `protobuf:"varint,18,opt,name=playtime_seconds,json=playtimeSeconds,proto3" json:"playtime_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CharacterData) Reset() {
	*x = CharacterData{}
	mi := &file_character_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterData) ProtoMessage() {}

func (x *CharacterData) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterData.ProtoReflect.Descriptor instead.
func (*CharacterData) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{9}
}

func (x *CharacterData) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *CharacterData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterData) GetClass() CharacterClass {
	if x != nil {
		return x.Class
	}
	return CharacterClass_CHARACTER_CLASS_UNSPECIFIED
}

func (x *CharacterData) GetRace() CharacterRace {
	if x != nil {
		return x.Race
	}
	return CharacterRace_CHARACTER_RACE_UNSPECIFIED
}

func (x *CharacterData) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *CharacterData) GetStats() *CharacterStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *CharacterData) GetAttributes() *CharacterAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CharacterData) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CharacterData) GetExperience() int64 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *CharacterData) GetExperienceToNextLevel() int64 {
	if x != nil {
		return x.ExperienceToNextLevel
	}
	return 0
}

func (x *CharacterData) GetLastTransform() *Transform {
	if x != nil {
		return x.LastTransform
	}
	return nil
}

func (x *CharacterData) GetLastZoneId() string {
	if x != nil {
		return x.LastZoneId
	}
	return ""
}

func (x *CharacterData) GetAppearance() *CharacterAppearance {
	if x != nil {
		return x.Appearance
	}
	return nil
}

func (x *CharacterData) GetEquippedItems() map[string]string {
	if x != nil {
		return x.EquippedItems
	}
	return nil
}

func (x *CharacterData) GetCurrencies() map[string]int64 {
	if x != nil {
		return x.Currencies
	}
	return nil
}

func (x *CharacterData) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CharacterData) GetLastPlayed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPlayed
	}
	return nil
}

func (x *CharacterData) GetPlaytimeSeconds() int64 {
	if x != nil {
		return x.PlaytimeSeconds
	}
	return 0
}

// Character appearance customization
type CharacterAppearance struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	FaceType  int32                  `protobuf:"varint,1,opt,name=face_type,json=faceType,proto3" json:"face_type,omitempty"`
	HairStyle int32                  `protobuf:"varint,2,opt,name=hair_style,json=hairStyle,proto3" json:"hair_style,omitempty"`
	HairColor int32                  `protobuf:"varint,3,opt,name=hair_color,json=hairColor,proto3" json:"hair_color,omitempty"`
	SkinColor int32                  `protobuf:"varint,4,opt,name=skin_color,json=skinColor,proto3" json:"skin_color,omitempty"`
	EyeColor  int32                  `protobuf:"varint,5,opt,name=eye_color,json=eyeColor,proto3" json:"eye_color,omitempty"`
	Height    float32                `protobuf:"fixed32,6,opt,name=height,proto3" json:"height,omitempty"` // Normalized 0-1
	Build     float32                `protobuf:"fixed32,7,opt,name=build,proto3" json:"build,omitempty"`   // Normalized 0-1
	// Additional customization options
	CustomOptions map[string]int32 `protobuf:"bytes,8,rep,name=custom_options,json=customOptions,proto3" json:"custom_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterAppearance) Reset() {
	*x = CharacterAppearance{}
	mi := &file_character_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterAppearance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterAppearance) ProtoMessage() {}

func (x *CharacterAppearance) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterAppearance.ProtoReflect.Descriptor instead.
func (*CharacterAppearance) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{10}
}

func (x *CharacterAppearance) GetFaceType() int32 {
	if x != nil {
		return x.FaceType
	}
	return 0
}

func (x *CharacterAppearance) GetHairStyle() int32 {
	if x != nil {
		return x.HairStyle
	}
	return 0
}

func (x *CharacterAppearance) GetHairColor() int32 {
	if x != nil {
		return x.HairColor
	}
	return 0
}

func (x *CharacterAppearance) GetSkinColor() int32 {
	if x != nil {
		return x.SkinColor
	}
	return 0
}

func (x *CharacterAppearance) GetEyeColor() int32 {
	if x != nil {
		return x.EyeColor
	}
	return 0
}

func (x *CharacterAppearance) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CharacterAppearance) GetBuild() float32 {
	if x != nil {
		return x.Build
	}
	return 0
}

func (x *CharacterAppearance) GetCustomOptions() map[string]int32 {
	if x != nil {
		return x.CustomOptions
	}
	return nil
}

// Character stats (combat related)
type CharacterStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Health          int32                  `protobuf:"varint,1,opt,name=health,proto3" json:"health,omitempty"`
	MaxHealth       int32                  `protobuf:"varint,2,opt,name=max_health,json=maxHealth,proto3" json:"max_health,omitempty"`
	Mana            int32                  `protobuf:"varint,3,opt,name=mana,proto3" json:"mana,omitempty"`
	MaxMana         int32                  `protobuf:"varint,4,opt,name=max_mana,json=maxMana,proto3" json:"max_mana,omitempty"`
	Stamina         int32                  `protobuf:"varint,5,opt,name=stamina,proto3" json:"stamina,omitempty"`
	MaxStamina      int32                  `protobuf:"varint,6,opt,name=max_stamina,json=maxStamina,proto3" json:"max_stamina,omitempty"`
	AttackPower     int32                  `protobuf:"varint,7,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`
	SpellPower      int32                  `protobuf:"varint,8,opt,name=spell_power,json=spellPower,proto3" json:"spell_power,omitempty"`
	Defense         int32                  `protobuf:"varint,9,opt,name=defense,proto3" json:"defense,omitempty"`
	MagicResistance int32                  `protobuf:"varint,10,opt,name=magic_resistance,json=magicResistance,proto3" json:"magic_resistance,omitempty"`
	CriticalChance  float32                `protobuf:"fixed32,11,opt,name=critical_chance,json=criticalChance,proto3" json:"critical_chance,omitempty"`
	CriticalDamage  float32                `protobuf:"fixed32,12,opt,name=critical_damage,json=criticalDamage,proto3" json:"critical_damage,omitempty"`
	DodgeChance     float32                `protobuf:"fixed32,13,opt,name=dodge_chance,json=dodgeChance,proto3" json:"dodge_chance,omitempty"`
	BlockChance     float32                `protobuf:"fixed32,14,opt,name=block_chance,json=blockChance,proto3" json:"block_chance,omitempty"`
	MovementSpeed   float32                `protobuf:"fixed32,15,opt,name=movement_speed,json=movementSpeed,proto3" json:"movement_speed,omitempty"`
	AttackSpeed     float32                `protobuf:"fixed32,16,opt,name=attack_speed,json=attackSpeed,proto3" json:"attack_speed,omitempty"`
	CastSpeed       float32                `protobuf:"fixed32,17,opt,name=cast_speed,json=castSpeed,proto3" json:"cast_speed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CharacterStats) Reset() {
	*x = CharacterStats{}
	mi := &file_character_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterStats) ProtoMessage() {}

func (x *CharacterStats) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterStats.ProtoReflect.Descriptor instead.
func (*CharacterStats) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{11}
}

func (x *CharacterStats) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *CharacterStats) GetMaxHealth() int32 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

func (x *CharacterStats) GetMana() int32 {
	if x != nil {
		return x.Mana
	}
	return 0
}

func (x *CharacterStats) GetMaxMana() int32 {
	if x != nil {
		return x.MaxMana
	}
	return 0
}

func (x *CharacterStats) GetStamina() int32 {
	if x != nil {
		return x.Stamina
	}
	return 0
}

func (x *CharacterStats) GetMaxStamina() int32 {
	if x != nil {
		return x.MaxStamina
	}
	return 0
}

func (x *CharacterStats) GetAttackPower() int32 {
	if x != nil {
		return x.AttackPower
	}
	return 0
}

func (x *CharacterStats) GetSpellPower() int32 {
	if x != nil {
		return x.SpellPower
	}
	return 0
}

func (x *CharacterStats) GetDefense() int32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *CharacterStats) GetMagicResistance() int32 {
	if x != nil {
		return x.MagicResistance
	}
	return 0
}

func (x *CharacterStats) GetCriticalChance() float32 {
	if x != nil {
		return x.CriticalChance
	}
	return 0
}

func (x *CharacterStats) GetCriticalDamage() float32 {
	if x != nil {
		return x.CriticalDamage
	}
	return 0
}

func (x *CharacterStats) GetDodgeChance() float32 {
	if x != nil {
		return x.DodgeChance
	}
	return 0
}

func (x *CharacterStats) GetBlockChance() float32 {
	if x != nil {
		return x.BlockChance
	}
	return 0
}

func (x *CharacterStats) GetMovementSpeed() float32 {
	if x != nil {
		return x.MovementSpeed
	}
	return 0
}

func (x *CharacterStats) GetAttackSpeed() float32 {
	if x != nil {
		return x.AttackSpeed
	}
	return 0
}

func (x *CharacterStats) GetCastSpeed() float32 {
	if x != nil {
		return x.CastSpeed
	}
	return 0
}

// Character attributes (base stats)
type CharacterAttributes struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Strength     int32                  `protobuf:"varint,1,opt,name=strength,proto3" json:"strength,omitempty"`
	Agility      int32                  `protobuf:"varint,2,opt,name=agility,proto3" json:"agility,omitempty"`
	Intelligence int32                  `protobuf:"varint,3,opt,name=intelligence,proto3" json:"intelligence,omitempty"`
	Wisdom       int32                  `protobuf:"varint,4,opt,name=wisdom,proto3" json:"wisdom,omitempty"`
	Constitution int32                  `protobuf:"varint,5,opt,name=constitution,proto3" json:"constitution,omitempty"`
	Charisma     int32                  `protobuf:"varint,6,opt,name=charisma,proto3" json:"charisma,omitempty"`
	// Points available to spend
	UnspentPoints int32 `protobuf:"varint,7,opt,name=unspent_points,json=unspentPoints,proto3" json:"unspent_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterAttributes) Reset() {
	*x = CharacterAttributes{}
	mi := &file_character_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterAttributes) ProtoMessage() {}

func (x *CharacterAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterAttributes.ProtoReflect.Descriptor instead.
func (*CharacterAttributes) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{12}
}

func (x *CharacterAttributes) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *CharacterAttributes) GetAgility() int32 {
	if x != nil {
		return x.Agility
	}
	return 0
}

func (x *CharacterAttributes) GetIntelligence() int32 {
	if x != nil {
		return x.Intelligence
	}
	return 0
}

func (x *CharacterAttributes) GetWisdom() int32 {
	if x != nil {
		return x.Wisdom
	}
	return 0
}

func (x *CharacterAttributes) GetConstitution() int32 {
	if x != nil {
		return x.Constitution
	}
	return 0
}

func (x *CharacterAttributes) GetCharisma() int32 {
	if x != nil {
		return x.Charisma
	}
	return 0
}

func (x *CharacterAttributes) GetUnspentPoints() int32 {
	if x != nil {
		return x.UnspentPoints
	}
	return 0
}

// Equipment preview for character select
type EquipmentPreview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          string                 `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	IconId        string                 `protobuf:"bytes,3,opt,name=icon_id,json=iconId,proto3" json:"icon_id,omitempty"`
	Quality       int32                  `protobuf:"varint,4,opt,name=quality,proto3" json:"quality,omitempty"` // Item quality/rarity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentPreview) Reset() {
	*x = EquipmentPreview{}
	mi := &file_character_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentPreview) ProtoMessage() {}

func (x *EquipmentPreview) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentPreview.ProtoReflect.Descriptor instead.
func (*EquipmentPreview) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{13}
}

func (x *EquipmentPreview) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *EquipmentPreview) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *EquipmentPreview) GetIconId() string {
	if x != nil {
		return x.IconId
	}
	return ""
}

func (x *EquipmentPreview) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

var File_character_proto protoreflect.FileDescriptor

const file_character_proto_rawDesc = "" +
	"\n" +
	"\x0fcharacter.proto\x12\x06mmorpg\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\n" +
	"base.proto\"N\n" +
	"\x14CharacterListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\xe6\x01\n" +
	"\x15CharacterListResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x125\n" +
	"\n" +
	"characters\x18\x02 \x03(\v2\x15.mmorpg.CharacterInfoR\n" +
	"characters\x12%\n" +
	"\x0emax_characters\x18\x03 \x01(\x05R\rmaxCharacters\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x120\n" +
	"\n" +
	"error_code\x18\x05 \x01(\x0e2\x11.mmorpg.ErrorCodeR\terrorCode\"\x89\x02\n" +
	"\x16CharacterCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x05class\x18\x02 \x01(\x0e2\x16.mmorpg.CharacterClassR\x05class\x12)\n" +
	"\x04race\x18\x03 \x01(\x0e2\x15.mmorpg.CharacterRaceR\x04race\x12&\n" +
	"\x06gender\x18\x04 \x01(\x0e2\x0e.mmorpg.GenderR\x06gender\x12;\n" +
	"\n" +
	"appearance\x18\x05 \x01(\v2\x1b.mmorpg.CharacterAppearanceR\n" +
	"appearance\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\"\xe8\x02\n" +
	"\x17CharacterCreateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x123\n" +
	"\tcharacter\x18\x02 \x01(\v2\x15.mmorpg.CharacterInfoR\tcharacter\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x120\n" +
	"\n" +
	"error_code\x18\x04 \x01(\x0e2\x11.mmorpg.ErrorCodeR\terrorCode\x12b\n" +
	"\x11validation_errors\x18\x05 \x03(\v25.mmorpg.CharacterCreateResponse.ValidationErrorsEntryR\x10validationErrors\x1aC\n" +
	"\x15ValidationErrorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\x16CharacterDeleteRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12+\n" +
	"\x11confirmation_code\x18\x03 \x01(\tR\x10confirmationCode\"\x7f\n" +
	"\x17CharacterDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x0e2\x11.mmorpg.ErrorCodeR\terrorCode\"Z\n" +
	"\x16CharacterSelectRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\x93\x02\n" +
	"\x17CharacterSelectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12<\n" +
	"\x0echaracter_data\x18\x02 \x01(\v2\x15.mmorpg.CharacterDataR\rcharacterData\x12(\n" +
	"\x10world_server_url\x18\x03 \x01(\tR\x0eworldServerUrl\x12\x1f\n" +
	"\vworld_token\x18\x04 \x01(\tR\n" +
	"worldToken\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x120\n" +
	"\n" +
	"error_code\x18\x06 \x01(\x0e2\x11.mmorpg.ErrorCodeR\terrorCode\"\xa0\x04\n" +
	"\rCharacterInfo\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x05class\x18\x03 \x01(\x0e2\x16.mmorpg.CharacterClassR\x05class\x12)\n" +
	"\x04race\x18\x04 \x01(\x0e2\x15.mmorpg.CharacterRaceR\x04race\x12&\n" +
	"\x06gender\x18\x05 \x01(\x0e2\x0e.mmorpg.GenderR\x06gender\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x05R\x05level\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vlast_played\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastPlayed\x12)\n" +
	"\x10playtime_seconds\x18\n" +
	" \x01(\x03R\x0fplaytimeSeconds\x12;\n" +
	"\n" +
	"appearance\x18\v \x01(\v2\x1b.mmorpg.CharacterAppearanceR\n" +
	"appearance\x12E\n" +
	"\x11equipment_preview\x18\f \x03(\v2\x18.mmorpg.EquipmentPreviewR\x10equipmentPreview\"\xf6\a\n" +
	"\rCharacterData\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x05class\x18\x03 \x01(\x0e2\x16.mmorpg.CharacterClassR\x05class\x12)\n" +
	"\x04race\x18\x04 \x01(\x0e2\x15.mmorpg.CharacterRaceR\x04race\x12&\n" +
	"\x06gender\x18\x05 \x01(\x0e2\x0e.mmorpg.GenderR\x06gender\x12,\n" +
	"\x05stats\x18\x06 \x01(\v2\x16.mmorpg.CharacterStatsR\x05stats\x12;\n" +
	"\n" +
	"attributes\x18\a \x01(\v2\x1b.mmorpg.CharacterAttributesR\n" +
	"attributes\x12\x14\n" +
	"\x05level\x18\b \x01(\x05R\x05level\x12\x1e\n" +
	"\n" +
	"experience\x18\t \x01(\x03R\n" +
	"experience\x127\n" +
	"\x18experience_to_next_level\x18\n" +
	" \x01(\x03R\x15experienceToNextLevel\x128\n" +
	"\x0elast_transform\x18\v \x01(\v2\x11.mmorpg.TransformR\rlastTransform\x12 \n" +
	"\flast_zone_id\x18\f \x01(\tR\n" +
	"lastZoneId\x12;\n" +
	"\n" +
	"appearance\x18\r \x01(\v2\x1b.mmorpg.CharacterAppearanceR\n" +
	"appearance\x12O\n" +
	"\x0eequipped_items\x18\x0e \x03(\v2(.mmorpg.CharacterData.EquippedItemsEntryR\requippedItems\x12E\n" +
	"\n" +
	"currencies\x18\x0f \x03(\v2%.mmorpg.CharacterData.CurrenciesEntryR\n" +
	"currencies\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vlast_played\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastPlayed\x12)\n" +
	"\x10playtime_seconds\x18\x12 \x01(\x03R\x0fplaytimeSeconds\x1a@\n" +
	"\x12EquippedItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fCurrenciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xf3\x02\n" +
	"\x13CharacterAppearance\x12\x1b\n" +
	"\tface_type\x18\x01 \x01(\x05R\bfaceType\x12\x1d\n" +
	"\n" +
	"hair_style\x18\x02 \x01(\x05R\thairStyle\x12\x1d\n" +
	"\n" +
	"hair_color\x18\x03 \x01(\x05R\thairColor\x12\x1d\n" +
	"\n" +
	"skin_color\x18\x04 \x01(\x05R\tskinColor\x12\x1b\n" +
	"\teye_color\x18\x05 \x01(\x05R\beyeColor\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x02R\x06height\x12\x14\n" +
	"\x05build\x18\a \x01(\x02R\x05build\x12U\n" +
	"\x0ecustom_options\x18\b \x03(\v2..mmorpg.CharacterAppearance.CustomOptionsEntryR\rcustomOptions\x1a@\n" +
	"\x12CustomOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xbb\x04\n" +
	"\x0eCharacterStats\x12\x16\n" +
	"\x06health\x18\x01 \x01(\x05R\x06health\x12\x1d\n" +
	"\n" +
	"max_health\x18\x02 \x01(\x05R\tmaxHealth\x12\x12\n" +
	"\x04mana\x18\x03 \x01(\x05R\x04mana\x12\x19\n" +
	"\bmax_mana\x18\x04 \x01(\x05R\amaxMana\x12\x18\n" +
	"\astamina\x18\x05 \x01(\x05R\astamina\x12\x1f\n" +
	"\vmax_stamina\x18\x06 \x01(\x05R\n" +
	"maxStamina\x12!\n" +
	"\fattack_power\x18\a \x01(\x05R\vattackPower\x12\x1f\n" +
	"\vspell_power\x18\b \x01(\x05R\n" +
	"spellPower\x12\x18\n" +
	"\adefense\x18\t \x01(\x05R\adefense\x12)\n" +
	"\x10magic_resistance\x18\n" +
	" \x01(\x05R\x0fmagicResistance\x12'\n" +
	"\x0fcritical_chance\x18\v \x01(\x02R\x0ecriticalChance\x12'\n" +
	"\x0fcritical_damage\x18\f \x01(\x02R\x0ecriticalDamage\x12!\n" +
	"\fdodge_chance\x18\r \x01(\x02R\vdodgeChance\x12!\n" +
	"\fblock_chance\x18\x0e \x01(\x02R\vblockChance\x12%\n" +
	"\x0emovement_speed\x18\x0f \x01(\x02R\rmovementSpeed\x12!\n" +
	"\fattack_speed\x18\x10 \x01(\x02R\vattackSpeed\x12\x1d\n" +
	"\n" +
	"cast_speed\x18\x11 \x01(\x02R\tcastSpeed\"\xee\x01\n" +
	"\x13CharacterAttributes\x12\x1a\n" +
	"\bstrength\x18\x01 \x01(\x05R\bstrength\x12\x18\n" +
	"\aagility\x18\x02 \x01(\x05R\aagility\x12\"\n" +
	"\fintelligence\x18\x03 \x01(\x05R\fintelligence\x12\x16\n" +
	"\x06wisdom\x18\x04 \x01(\x05R\x06wisdom\x12\"\n" +
	"\fconstitution\x18\x05 \x01(\x05R\fconstitution\x12\x1a\n" +
	"\bcharisma\x18\x06 \x01(\x05R\bcharisma\x12%\n" +
	"\x0eunspent_points\x18\a \x01(\x05R\runspentPoints\"r\n" +
	"\x10EquipmentPreview\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x17\n" +
	"\aicon_id\x18\x03 \x01(\tR\x06iconId\x12\x18\n" +
	"\aquality\x18\x04 \x01(\x05R\aquality*\x90\x02\n" +
	"\x0eCharacterClass\x12\x1f\n" +
	"\x1bCHARACTER_CLASS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CHARACTER_CLASS_WARRIOR\x10\x01\x12\x18\n" +
	"\x14CHARACTER_CLASS_MAGE\x10\x02\x12\x1a\n" +
	"\x16CHARACTER_CLASS_ARCHER\x10\x03\x12\x19\n" +
	"\x15CHARACTER_CLASS_ROGUE\x10\x04\x12\x1a\n" +
	"\x16CHARACTER_CLASS_PRIEST\x10\x05\x12\x1b\n" +
	"\x17CHARACTER_CLASS_PALADIN\x10\x06\x12\x1b\n" +
	"\x17CHARACTER_CLASS_WARLOCK\x10\a\x12\x19\n" +
	"\x15CHARACTER_CLASS_DRUID\x10\b*\xff\x01\n" +
	"\rCharacterRace\x12\x1e\n" +
	"\x1aCHARACTER_RACE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CHARACTER_RACE_HUMAN\x10\x01\x12\x16\n" +
	"\x12CHARACTER_RACE_ELF\x10\x02\x12\x18\n" +
	"\x14CHARACTER_RACE_DWARF\x10\x03\x12\x16\n" +
	"\x12CHARACTER_RACE_ORC\x10\x04\x12\x18\n" +
	"\x14CHARACTER_RACE_GNOME\x10\x05\x12\x19\n" +
	"\x15CHARACTER_RACE_UNDEAD\x10\x06\x12\x18\n" +
	"\x14CHARACTER_RACE_TROLL\x10\a\x12\x1b\n" +
	"\x17CHARACTER_RACE_HALFLING\x10\b*V\n" +
	"\x06Gender\x12\x16\n" +
	"\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vGENDER_MALE\x10\x01\x12\x11\n" +
	"\rGENDER_FEMALE\x10\x02\x12\x10\n" +
	"\fGENDER_OTHER\x10\x03B.Z,github.com/mmorpg-template/backend/pkg/protob\x06proto3"

var (
	file_character_proto_rawDescOnce sync.Once
	file_character_proto_rawDescData []byte
)

func file_character_proto_rawDescGZIP() []byte {
	file_character_proto_rawDescOnce.Do(func() {
		file_character_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_character_proto_rawDesc), len(file_character_proto_rawDesc)))
	})
	return file_character_proto_rawDescData
}

var file_character_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_character_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_character_proto_goTypes = []any{
	(CharacterClass)(0),             // 0: mmorpg.CharacterClass
	(CharacterRace)(0),              // 1: mmorpg.CharacterRace
	(Gender)(0),                     // 2: mmorpg.Gender
	(*CharacterListRequest)(nil),    // 3: mmorpg.CharacterListRequest
	(*CharacterListResponse)(nil),   // 4: mmorpg.CharacterListResponse
	(*CharacterCreateRequest)(nil),  // 5: mmorpg.CharacterCreateRequest
	(*CharacterCreateResponse)(nil), // 6: mmorpg.CharacterCreateResponse
	(*CharacterDeleteRequest)(nil),  // 7: mmorpg.CharacterDeleteRequest
	(*CharacterDeleteResponse)(nil), // 8: mmorpg.CharacterDeleteResponse
	(*CharacterSelectRequest)(nil),  // 9: mmorpg.CharacterSelectRequest
	(*CharacterSelectResponse)(nil), // 10: mmorpg.CharacterSelectResponse
	(*CharacterInfo)(nil),           // 11: mmorpg.CharacterInfo
	(*CharacterData)(nil),           // 12: mmorpg.CharacterData
	(*CharacterAppearance)(nil),     // 13: mmorpg.CharacterAppearance
	(*CharacterStats)(nil),          // 14: mmorpg.CharacterStats
	(*CharacterAttributes)(nil),     // 15: mmorpg.CharacterAttributes
	(*EquipmentPreview)(nil),        // 16: mmorpg.EquipmentPreview
	nil,                             // 17: mmorpg.CharacterCreateResponse.ValidationErrorsEntry
	nil,                             // 18: mmorpg.CharacterData.EquippedItemsEntry
	nil,                             // 19: mmorpg.CharacterData.CurrenciesEntry
	nil,                             // 20: mmorpg.CharacterAppearance.CustomOptionsEntry
	(ErrorCode)(0),                  // 21: mmorpg.ErrorCode
	(*timestamppb.Timestamp)(nil),   // 22: google.protobuf.Timestamp
	(*Transform)(nil),               // 23: mmorpg.Transform
}
var file_character_proto_depIdxs = []int32{
	11, // 0: mmorpg.CharacterListResponse.characters:type_name -> mmorpg.CharacterInfo
	21, // 1: mmorpg.CharacterListResponse.error_code:type_name -> mmorpg.ErrorCode
	0,  // 2: mmorpg.CharacterCreateRequest.class:type_name -> mmorpg.CharacterClass
	1,  // 3: mmorpg.CharacterCreateRequest.race:type_name -> mmorpg.CharacterRace
	2,  // 4: mmorpg.CharacterCreateRequest.gender:type_name -> mmorpg.Gender
	13, // 5: mmorpg.CharacterCreateRequest.appearance:type_name -> mmorpg.CharacterAppearance
	11, // 6: mmorpg.CharacterCreateResponse.character:type_name -> mmorpg.CharacterInfo
	21, // 7: mmorpg.CharacterCreateResponse.error_code:type_name -> mmorpg.ErrorCode
	17, // 8: mmorpg.CharacterCreateResponse.validation_errors:type_name -> mmorpg.CharacterCreateResponse.ValidationErrorsEntry
	21, // 9: mmorpg.CharacterDeleteResponse.error_code:type_name -> mmorpg.ErrorCode
	12, // 10: mmorpg.CharacterSelectResponse.character_data:type_name -> mmorpg.CharacterData
	21, // 11: mmorpg.CharacterSelectResponse.error_code:type_name -> mmorpg.ErrorCode
	0,  // 12: mmorpg.CharacterInfo.class:type_name -> mmorpg.CharacterClass
	1,  // 13: mmorpg.CharacterInfo.race:type_name -> mmorpg.CharacterRace
	2,  // 14: mmorpg.CharacterInfo.gender:type_name -> mmorpg.Gender
	22, // 15: mmorpg.CharacterInfo.created_at:type_name -> google.protobuf.Timestamp
	22, // 16: mmorpg.CharacterInfo.last_played:type_name -> google.protobuf.Timestamp
	13, // 17: mmorpg.CharacterInfo.appearance:type_name -> mmorpg.CharacterAppearance
	16, // 18: mmorpg.CharacterInfo.equipment_preview:type_name -> mmorpg.EquipmentPreview
	0,  // 19: mmorpg.CharacterData.class:type_name -> mmorpg.CharacterClass
	1,  // 20: mmorpg.CharacterData.race:type_name -> mmorpg.CharacterRace
	2,  // 21: mmorpg.CharacterData.gender:type_name -> mmorpg.Gender
	14, // 22: mmorpg.CharacterData.stats:type_name -> mmorpg.CharacterStats
	15, // 23: mmorpg.CharacterData.attributes:type_name -> mmorpg.CharacterAttributes
	23, // 24: mmorpg.CharacterData.last_transform:type_name -> mmorpg.Transform
	13, // 25: mmorpg.CharacterData.appearance:type_name -> mmorpg.CharacterAppearance
	18, // 26: mmorpg.CharacterData.equipped_items:type_name -> mmorpg.CharacterData.EquippedItemsEntry
	19, // 27: mmorpg.CharacterData.currencies:type_name -> mmorpg.CharacterData.CurrenciesEntry
	22, // 28: mmorpg.CharacterData.created_at:type_name -> google.protobuf.Timestamp
	22, // 29: mmorpg.CharacterData.last_played:type_name -> google.protobuf.Timestamp
	20, // 30: mmorpg.CharacterAppearance.custom_options:type_name -> mmorpg.CharacterAppearance.CustomOptionsEntry
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_character_proto_init() }
func file_character_proto_init() {
	if File_character_proto != nil {
		return
	}
	file_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_character_proto_rawDesc), len(file_character_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_character_proto_goTypes,
		DependencyIndexes: file_character_proto_depIdxs,
		EnumInfos:         file_character_proto_enumTypes,
		MessageInfos:      file_character_proto_msgTypes,
	}.Build()
	File_character_proto = out.File
	file_character_proto_goTypes = nil
	file_character_proto_depIdxs = nil
}
