version: 2
updates:
  # Go dependencies
  - package-ecosystem: "gomod"
    directory: "/mmorpg-backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 5
    reviewers:
      - "mmorpg-maintainers"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 5
    reviewers:
      - "mmorpg-maintainers"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/mmorpg-backend/build/docker/gateway"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
    open-pull-requests-limit: 3
    reviewers:
      - "mmorpg-maintainers"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build"